const SAVE_ARTICLE = 'CREATE_ARTICLE';
const DELETE_ARTICLE = 'DELETE_ARTICLE';
const UPDATE_WATCHED_STATUS = 'UPDATE_WATCHED_STATUS';
const UPDATE_LIKED_STATUS = 'UPDATE_LIKED_STATUS';

export {
  SAVE_ARTICLE,
  DELETE_ARTICLE,
  UPDATE_WATCHED_STATUS,
  UPDATE_LIKED_STATUS,
};
