const GET_RECENT_KEYWORDS = 'GET_RECENT_KEYWORDS';
const SAVE_RECENT_KEYWORDS = 'SAVE_RECENT_KEYWORDS';
const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export {
  GET_RECENT_KEYWORDS,
  SAVE_RECENT_KEYWORDS,
  UPDATE_SEARCH_RESULTS,
};
